<?

namespace IMAGA\Theme\ACF;

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c41b9910b8a5',
	'title' => 'Activiteit Informatie',
	'fields' => array(
		array(
			'key' => 'field_5c41b99a47951',
			'label' => 'Wanneer',
			'name' => 'date_time',
			'type' => 'date_time_picker',
			'instructions' => 'Voer hier in wanneer de activiteit plaatsvindt.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y g:i a',
			'return_format' => 'j F',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'activities',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3dcfef83b13',
	'title' => 'Employee info',
	'fields' => array(
		array(
			'key' => 'field_5c3dcff7460c8',
			'label' => 'Voornaam',
			'name' => 'firstname',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3dd000460c9',
			'label' => 'Achternaam',
			'name' => 'lastname',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'employees',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3f3442140f2',
	'title' => 'Feiten Element',
	'fields' => array(
		array(
			'key' => 'field_5c3f3819d5981',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3f3942d5982',
			'label' => 'Layout Selectie',
			'name' => 'layout_selector',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				2 => '2 Feiten',
				3 => '3 Feiten',
				5 => '5 Feiten',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5c4059804b3b5',
			'label' => '2 Feiten',
			'name' => 'layout_2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c3f3942d5982',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c4059d54b3b7',
					'label' => '',
					'name' => 'fact_1',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c40599d4b3b6',
							'label' => 'Feit 1',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c4059f64b3b8',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
				),
				array(
					'key' => 'field_5c405a6d4b3bc',
					'label' => '',
					'name' => 'fact_2',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405a6d4b3bd',
							'label' => 'Feit 2',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405a6d4b3be',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5c405bf5f3305',
			'label' => '3 Feiten',
			'name' => 'layout_3',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c3f3942d5982',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c405bf5f3306',
					'label' => '',
					'name' => 'fact_1',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405bf5f3307',
							'label' => 'Feit 1',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405bf5f3308',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => '',
							'return_format' => '',
						),
					),
				),
				array(
					'key' => 'field_5c405bf5f3309',
					'label' => '',
					'name' => 'fact_2',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405bf5f330a',
							'label' => 'Feit 2',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405bf5f330b',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => '',
							'return_format' => '',
						),
					),
				),
				array(
					'key' => 'field_5c405d105de51',
					'label' => '',
					'name' => 'fact_3',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405d105de52',
							'label' => 'Feit 3',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405d105de53',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5c405bfff330c',
			'label' => '5 Feiten',
			'name' => 'layout_5',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c3f3942d5982',
						'operator' => '==',
						'value' => '5',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c405bfff330d',
					'label' => '',
					'name' => 'fact_1',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405bfff330e',
							'label' => 'Feit 1',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405bfff330f',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
				),
				array(
					'key' => 'field_5c405bfff3310',
					'label' => '',
					'name' => 'fact_2',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405bfff3311',
							'label' => 'Feit 2',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405bfff3312',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => '',
							'return_format' => '',
						),
					),
				),
				array(
					'key' => 'field_5c405c0af3313',
					'label' => '',
					'name' => 'fact_3',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405c0af3314',
							'label' => 'Feit 2',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405c0af3315',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => '',
							'return_format' => '',
						),
					),
				),
				array(
					'key' => 'field_5c405c0df3316',
					'label' => '',
					'name' => 'fact_4',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405c0df3317',
							'label' => 'Feit 2',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405c0df3318',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => '',
							'return_format' => '',
						),
					),
				),
				array(
					'key' => 'field_5c405c0ff3319',
					'label' => '',
					'name' => 'fact_5',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c405c0ff331a',
							'label' => 'Feit 2',
							'name' => 'post',
							'type' => 'post_object',
							'instructions' => 'Kies een van de boerderij feiten.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'facts',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_5c405c0ff331b',
							'label' => 'Kleur',
							'name' => 'color',
							'type' => 'button_group',
							'instructions' => 'Kier hier de kleur van het blok.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'green' => 'Groen',
								'yellow' => 'Geel',
								'blue' => 'Blauw',
							),
							'allow_null' => 0,
							'default_value' => 'green',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3db8a43465a',
	'title' => 'Gallerij Element',
	'fields' => array(
		array(
			'key' => 'field_5c3db8b767e1b',
			'label' => 'Pre-Titel',
			'name' => 'pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3db8ac67e1a',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3db8ce67e1c',
			'label' => 'Slides',
			'name' => 'slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c3db90d67e1d',
			'min' => 2,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Slide toevoegen',
			'sub_fields' => array(
				array(
					'key' => 'field_5c3db95b67e1f',
					'label' => 'Afbeelding',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c3db90d67e1d',
					'label' => 'Titel',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c3db93767e1e',
					'label' => 'Onderschrift',
					'name' => 'description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c34a33905305',
	'title' => 'Globale Instellingen',
	'fields' => array(
		array(
			'key' => 'field_5c34a3452f3c9',
			'label' => 'Keurmerken',
			'name' => 'quality_marks',
			'type' => 'repeater',
			'instructions' => 'Voeg hier de merken van het bedrijf toe. Dit zijn de zegels die onder andere in de footer te zien zijn.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c34a3c52f3cc',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5c34a3c52f3cc',
					'label' => 'Afbeelding',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c3ddf78c3ed3',
					'label' => 'Link',
					'name' => 'url',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
				),
			),
		),
		array(
			'key' => 'field_5c3da3037016b',
			'label' => 'Vacature Link Tekst',
			'name' => 'vacancy_promo',
			'type' => 'text',
			'instructions' => 'Voer hier de tekst in voor de vacature link.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Wil jij bij ons werken? Bekijk onze	<a href="/vacatures">vacatures</a>',
			'placeholder' => 'Wil jij bij ons werken? Bekijk onze	<a href="/vacatures">vacatures</a>',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'degelder-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c41a7342e6d7',
	'title' => 'Lijst Element',
	'fields' => array(
		array(
			'key' => 'field_5c41a9e659a7c',
			'label' => 'Pre-Titel',
			'name' => 'pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c41a75b81be4',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c41a9f659a7d',
			'label' => 'Lijsten',
			'name' => 'lists',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c41aa0259a7e',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Lijst toevoegen',
			'sub_fields' => array(
				array(
					'key' => 'field_5c41aa0259a7e',
					'label' => 'Lijst Titel',
					'name' => 'list_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c41a76381be5',
					'label' => 'Bestanden',
					'name' => 'files',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5c41a77081be6',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Bestand toevoegen',
					'sub_fields' => array(
						array(
							'key' => 'field_5c41a77d81be7',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'quality-mark',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5c41a77081be6',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'Voer hier de titel in van het bestand.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c41a7912c75a',
							'label' => 'Bestand',
							'name' => 'file',
							'type' => 'file',
							'instructions' => 'Upload hier het bestand voor het product',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3e0486027ee',
	'title' => 'Pagina\'s Display',
	'fields' => array(
		array(
			'key' => 'field_5c3e03dc27d56',
			'label' => 'Pagina\'s',
			'name' => 'featured_pages',
			'type' => 'repeater',
			'instructions' => 'Kies hier de uitgelichte pagina\'s.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c3e03dce920b',
			'min' => 3,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5c3e03dce551d',
					'label' => 'Pagina',
					'name' => 'featured_page',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array(
					'key' => 'field_5c3e03dce920b',
					'label' => 'Titel',
					'name' => 'featured_page_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c3e03dcecf3f',
					'label' => 'Omschrijving',
					'name' => 'featured_page_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3f4ba9bac9b',
	'title' => 'Posttype Facts',
	'fields' => array(
		array(
			'key' => 'field_5c3f4beb235d8',
			'label' => 'Afbeelding',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'facts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c41b64641eb2',
	'title' => 'RPA Combinatie Element',
	'fields' => array(
		array(
			'key' => 'field_5c41b64802e7a',
			'label' => 'Reviews Titel',
			'name' => 'title_reviews',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c41b67802e7c',
			'label' => 'Agenda Titel',
			'name' => 'title_agenda',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c41b6a202e7d',
			'label' => 'Uitgelicht product',
			'name' => 'featured_product',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'product',
			),
			'taxonomy' => array(
				0 => 'product_visibility:featured',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5c41b66502e7b',
			'label' => 'Uitgelicht product Titel',
			'name' => 'title_product',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c41b6dc02e7e',
			'label' => 'Uitgelicht product Tekst',
			'name' => 'featured_product_content',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3dc207ec3bd',
	'title' => 'Section steps',
	'fields' => array(
		array(
			'key' => 'field_5c3dc20eeb2e9',
			'label' => 'Pre-Titel',
			'name' => 'pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3dc21eeb2ea',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3dc226eb2eb',
			'label' => 'Stappen',
			'name' => 'steps',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c3dc284eb2ef',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Stap toevoegen',
			'sub_fields' => array(
				array(
					'key' => 'field_5c3dc272eb2ee',
					'label' => 'Tekst',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5c3dc284eb2ef',
					'label' => 'Afbeelding',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c668c1714b1a',
	'title' => 'Shop Pagina',
	'fields' => array(
		array(
			'key' => 'field_5c668c5f7014e',
			'label' => 'Verzending Promotie',
			'name' => 'shipping_promo',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c668c4d7014d',
					'label' => 'Afbeelding',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c668c227014c',
					'label' => 'Tekst',
					'name' => 'content',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5c668cae7014f',
			'label' => 'Boerderijwinkel Promotie',
			'name' => 'shop_promo',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c668ccb70150',
					'label' => 'Afbeelding',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c668cde70151',
					'label' => 'Tekst',
					'name' => 'content',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'woo_shop_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c65800bf1a77',
	'title' => 'Social Media',
	'fields' => array(
		array(
			'key' => 'field_5c65801581487',
			'label' => 'Diensten',
			'name' => 'services',
			'type' => 'repeater',
			'instructions' => 'Voer hier de social media accounts in die De Gelder gebruikt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Dienst toevoegen',
			'sub_fields' => array(
				array(
					'key' => 'field_5c65804681488',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'file',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c65808281489',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c65808c8148a',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'degelder-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c387afee2abe',
	'title' => 'Taxonomy Employees Group',
	'fields' => array(
		array(
			'key' => 'field_5c387b56def49',
			'label' => 'Afbeelding',
			'name' => 'image',
			'type' => 'image',
			'instructions' => 'Deze afbeelding word gebruikt voor het Werknemers Display element.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'group',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c386cffd9654',
	'title' => 'Tekst Element',
	'fields' => array(
		array(
			'key' => 'field_5c386d0dc6142',
			'label' => 'Inhoud',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c386e00c6146',
			'label' => 'Tekst',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5c386d22c6143',
			'label' => 'Instellingen',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c386dbcc6145',
			'label' => 'Afbeelding',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c386d35c6144',
			'label' => 'Links/Rechts',
			'name' => 'toggle',
			'type' => 'button_group',
			'instructions' => 'Kies de plaatsing van de afbeelding t.o.v de tekst.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Links',
				'right' => 'Rechts',
			),
			'allow_null' => 0,
			'default_value' => 'links',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c34c0312a7ce',
	'title' => 'Titel Element',
	'fields' => array(
		array(
			'key' => 'field_5c34c03e150e8',
			'label' => 'Pre-titel',
			'name' => 'pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c34c054150e9',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c34c80951bb0',
	'title' => 'Uitgelicht Product',
	'fields' => array(
		array(
			'key' => 'field_5c37032a7d6cc',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3703377d6cd',
			'label' => 'Subtitel',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c34c8105d7e9',
			'label' => 'Product',
			'name' => 'product',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'product',
			),
			'taxonomy' => array(
				0 => 'product_visibility:featured',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c34c8cbb7b4f',
	'title' => 'Uitgelichte productafbeelding',
	'fields' => array(
		array(
			'key' => 'field_5c34c8dc160f4',
			'label' => 'Afbeelding',
			'name' => 'featured_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c6bd1da794bd',
	'title' => 'Voedingswaarden',
	'fields' => array(
		array(
			'key' => 'field_5c6bd1f72ce1f',
			'label' => 'Lijsten',
			'name' => 'lists',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c6bd21b2ce20',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Nieuwe lijst',
			'sub_fields' => array(
				array(
					'key' => 'field_5c6bd21b2ce20',
					'label' => 'Lijstlabel',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c6bd23e2ce21',
					'label' => 'Items',
					'name' => 'items',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5c6bd24c2ce22',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Nieuw item',
					'sub_fields' => array(
						array(
							'key' => 'field_5c6bd24c2ce22',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c6bd2682ce23',
							'label' => 'Waarde',
							'name' => 'value',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3878afb15d7',
	'title' => 'Werknemers Display',
	'fields' => array(
		array(
			'key' => 'field_5c3878c733560',
			'label' => 'Pre-titel',
			'name' => 'pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3878bc3355f',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c38791039ea3',
			'label' => 'Werknemers',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Dit wordt automatisch ingevuld door de informatie die is ingesteld bij de werknemers.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3dcbdc31645',
	'title' => 'Werknemers Lijst',
	'fields' => array(
		array(
			'key' => 'field_5c3dcbdc4bca3',
			'label' => 'Pre-titel',
			'name' => 'pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3dcbdc4f9d4',
			'label' => 'Titel',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c3dcbdc53695',
			'label' => 'Werknemersgroep',
			'name' => 'employees_group',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'group',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c6bd01b52857',
	'title' => 'Activiteiten en Vacatures pagina',
	'fields' => array(
		array(
			'key' => 'field_5c6bd01b8be53',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c6bd01b8fb67',
			'label' => '',
			'name' => 'header_background_image',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c6bd01be3a29',
					'label' => 'Achtergrond Afbeelding',
					'name' => 'header_image',
					'type' => 'image',
					'instructions' => 'Deze afbeelding werk enkel op de pagina zelf gebruikt.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c6bd01be7761',
					'label' => 'Titel',
					'name' => 'header_title',
					'type' => 'textarea',
					'instructions' => 'Voer hier de titel in voor over de afbeelding.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
			),
		),
		array(
			'key' => 'field_5c6bd01b9388c',
			'label' => 'Inhoud',
			'name' => 'header_content',
			'type' => 'wysiwyg',
			'instructions' => 'Voer hier de tekst in voor de zijbalk.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5c6bd01b975b3',
			'label' => 'Inhoud Onder',
			'name' => 'header_sub_content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5c6bd01b9b288',
			'label' => 'Achtergrond kleuren',
			'name' => 'header_background_color',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c6bd01c844a4',
					'label' => 'Inhoud rechterkant',
					'name' => 'content',
					'type' => 'button_group',
					'instructions' => 'Kies een kleur voor de achtergrond voor de inhoud aan de rechterkant.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'green-light' => 'Groen',
						'yellow-light' => 'Geel',
						'cyan' => 'Blauw',
					),
					'allow_null' => 0,
					'default_value' => 'cyan',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5c6bd01c881b9',
					'label' => 'Inhoud onderkant',
					'name' => 'sub_content',
					'type' => 'button_group',
					'instructions' => 'Kies een kleur voor de achtergrond voor de inhoud aan de onderkant.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c6bd01b975b3',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'green-light' => 'Groen',
						'yellow-light' => 'Geel',
						'cyan' => 'Blauw',
					),
					'allow_null' => 0,
					'default_value' => 'cyan',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_5c6bd01b9ef92',
			'label' => 'Inhoud',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c6bd03791c47',
			'label' => 'Informatie',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Deze pagina word automatisch gevuld met items.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-activiteiten.php',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-vacatures.php',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c3db9a74fd19',
	'title' => 'Standaard Pagina',
	'fields' => array(
		array(
			'key' => 'field_5c4090a7ec4fd',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c40918cf0bb3',
			'label' => '',
			'name' => 'header_background_image',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c408bf6a8c8d',
					'label' => 'Achtergrond Afbeelding',
					'name' => 'header_image',
					'type' => 'image',
					'instructions' => 'Deze afbeelding werk enkel op de pagina zelf gebruikt.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c408b49212c6',
					'label' => 'Titel',
					'name' => 'header_title',
					'type' => 'textarea',
					'instructions' => 'Voer hier de titel in voor over de afbeelding.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
			),
		),
		array(
			'key' => 'field_5c408b4924faf',
			'label' => 'Inhoud',
			'name' => 'header_content',
			'type' => 'wysiwyg',
			'instructions' => 'Voer hier de tekst in voor de zijbalk.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5c408c8ea8c8f',
			'label' => 'Inhoud Onder',
			'name' => 'header_sub_content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5c40a1d1a605c',
			'label' => 'Achtergrond kleuren',
			'name' => 'header_background_color',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c40a0f5fbd96',
					'label' => 'Inhoud rechterkant',
					'name' => 'content',
					'type' => 'button_group',
					'instructions' => 'Kies een kleur voor de achtergrond voor de inhoud aan de rechterkant.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'green-light' => 'Groen',
						'yellow-light' => 'Geel',
						'cyan' => 'Blauw',
					),
					'allow_null' => 0,
					'default_value' => 'cyan',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5c40a15cfbd97',
					'label' => 'Inhoud onderkant',
					'name' => 'sub_content',
					'type' => 'button_group',
					'instructions' => 'Kies een kleur voor de achtergrond voor de inhoud aan de onderkant.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c408c8ea8c8f',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'green-light' => 'Groen',
						'yellow-light' => 'Geel',
						'cyan' => 'Blauw',
					),
					'allow_null' => 0,
					'default_value' => 'cyan',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_5c409094ec4fc',
			'label' => 'Inhoud',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c3db9a778eef',
			'label' => 'Sections',
			'name' => 'sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5c34bc3985f8c' => array(
					'key' => '5c34bc3985f8c',
					'name' => 'title',
					'label' => 'Titel Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3db9a7bd9ac',
							'label' => 'Clone title',
							'name' => 'clone_title',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c34c0312a7ce',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c386e2c50c23' => array(
					'key' => 'layout_5c386e2c50c23',
					'name' => 'content',
					'label' => 'Tekst Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3db9a7bde35',
							'label' => 'Clone content',
							'name' => 'clone_content',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c386cffd9654',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c3dba1df9138' => array(
					'key' => 'layout_5c3dba1df9138',
					'name' => 'gallery',
					'label' => 'Gallerij Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3dba1df9139',
							'label' => 'Clone Gallery',
							'name' => 'clone_gallery',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c3db8a43465a',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c3dc30761c36' => array(
					'key' => 'layout_5c3dc30761c36',
					'name' => 'steps',
					'label' => 'Stappen',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3dc30761c37',
							'label' => 'Clone Steps',
							'name' => 'clone_steps',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c3dc207ec3bd',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c41a896cb190' => array(
					'key' => 'layout_5c41a896cb190',
					'name' => 'file-list',
					'label' => 'Lijst Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c41a896cb191',
							'label' => 'Clone File List',
							'name' => 'clone_file_list',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c41a7342e6d7',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c34c8553893c' => array(
					'key' => 'layout_5c34c8553893c',
					'name' => 'featured-product',
					'label' => 'Product Display',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3db9a7bda4a',
							'label' => 'Clone featured product',
							'name' => 'clone_featured_product',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c34c80951bb0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c38798e57c87' => array(
					'key' => 'layout_5c38798e57c87',
					'name' => 'employees-display',
					'label' => 'Werknemers Display',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3db9a7be22d',
							'label' => 'Clone Werknemers Display',
							'name' => 'clone_employees_display',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c3878afb15d7',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c3dcc6e77ffd' => array(
					'key' => 'layout_5c3dcc6e77ffd',
					'name' => 'employees-list',
					'label' => 'Werknemers Lijst',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3dcc6e77ffe',
							'label' => 'Clone Werknemers List',
							'name' => 'clone_employees_list',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c3dcbdc31645',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c3f3209936a9' => array(
					'key' => 'layout_5c3f3209936a9',
					'name' => 'vacancy-promo',
					'label' => 'Vacature Link',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3f3258936ab',
							'label' => 'Vacature Link',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Dit is slechts een plaatshouder. De tekst kan ja aanpassen op de <a href="/wp-admin/admin.php?page=degelder-options">Thema Instellingen</a> pagina.',
							'new_lines' => '',
							'esc_html' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c3f4e9dd533a' => array(
					'key' => 'layout_5c3f4e9dd533a',
					'name' => 'facts',
					'label' => 'Feiten Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3f4eb1d533c',
							'label' => 'Clone Facts',
							'name' => 'clone_facts',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c3f3442140f2',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c3f51071f954' => array(
					'key' => 'layout_5c3f51071f954',
					'name' => 'featured-pages',
					'label' => 'Pagina\'s Display',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c3f51071f955',
							'label' => 'Clone Featured Pages',
							'name' => 'clone_featured_pages',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c3e0486027ee',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c40ac0cd9afa' => array(
					'key' => 'layout_5c40ac0cd9afa',
					'name' => 'reviews-product-agenda',
					'label' => 'RPA Combinatie Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c41b72005277',
							'label' => 'Clone: RPA',
							'name' => 'clone_rpa',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c41b64641eb2',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Sectie toevoegen',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
			array(
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'woo_shop_page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;
